map.language: AF
map.version: "http://identifiers.org/combine.specifications/sbgn.af.level-1.version-1.2"
glyph:
 class:
  __location__: shape
  rectangle: biological activity
arc:
 class:
  __location__: shape
  none: consumption
  standard: production
  delta: production
  white_diamond: modulation
